- name: Add Application to ArgoCD
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: "{{ project }}"
        namespace: argocd
        finalizers:
          - resources-finalizer.argocd.argoproj.io
        annotations:
          argocd-image-updater.argoproj.io/image-list: app=gcr.io/{{ projectid}}/{{ project }}
          argocd-image-updater.argoproj.io/app.update-strategy: latest
          argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
          argocd-image-updater.argoproj.io/app.allow-tags: regexp:^{{ process }}-[0-9].[0-9].[0-9]
          argocd-image-updater.argoproj.io/git-branch: main
          argocd-image-updater.argoproj.io/app.force-update: "true"
          argocd.argoproj.io/sync-options: Prune=true
      spec:
        project: default
        source:
          repoURL: git@github.com:gallitnet/argocd-deployments.git
          targetRevision: HEAD
          path: "{{ project }}/{{ process }}"
        destination:
          server: https://kubernetes.default.svc
          namespace: "{{ project }}"
        syncPolicy:
          syncOptions:
          - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true
            allowEmpty: true

