- name: Create Namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ project }}"
- name: Create secrets 
  shell: kubectl get secret gcr-json-key --namespace argocd -o yaml | grep -v '^\s*namespace:\s' |kubectl apply --namespace {{ project }} -f -
  ignore_errors: true      

