name: "Add app to ArgoCD"
description: "Running a deployment process"
inputs:
  token:
    description: "github-token"
    required: true
  username:
    description: "Git username"
    required: true
  projectid:
    description: "Project ID"
    required: true
  project:
    description: "project name"
    required: true
  owner:
    description: "github owner"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.username }}
    - ${{ inputs.projectid }}
    - ${{ inputs.project }}
    - ${{ inputs.owner }}
